

#ifndef __UI_EXTRA_WINDOW_IDS__
#define __UI_EXTRA_WINDOW_IDS__

#define START_SERVER_BUTTON			1009
#define SEND_FILE_BUTTON			1010

#define SET_SERVER_CLIENT_PORT_LABEL	1011
#define SET_SERVER_CLIENT_PORT_EDIT		1012


#define SET_CLIENT_CONNECT_ADDRESS_LABEL	1013
#define SET_CLIENT_CONNECT_ADDRESS_EDIT		1014

#define UPDATE_SERVER_CLIENT_PORT_BUTTON 1015
#define UPDATE_CLIENT_CONNECT_ADDRESS_BUTTON 1016


#define CREATE_BASE_MODEL_FILE_BUTTON 1017

#endif
